# Generated by Django 4.2.3 on 2023-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='input',
            field=models.CharField(default='отсутствует', max_length=50),
        ),
        migrations.AlterField(
            model_name='output',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='output',
            name='info',
            field=models.CharField(max_length=254),
        ),
    ]
